export const USER_KEY = 'user'
export const USER_ACCESS_TOKEN = 'access_token'
export const USER_REFRESH_TOKEN = 'refresh_token'
export const USER_LANGUAGE = 'user_language'
export const REFRESH_TOKEN_KEY = 'refresh_token'
